name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-2019

    env:
      SolutionFile: NetOfficeBuildTasks.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1

    - name: Build
      run: msbuild $env:SolutionFile /restore /m /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
