name: build

on:
  push:
  pull_request:
    branches: [ main ]

jobs:

  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-2022

    env:
      Configuration: ${{ matrix.configuration }}
      VersionSuffix: 'preview-${{ github.run_number }}'

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8

    - name: setup msbuild
      uses: microsoft/setup-msbuild@v2

    - name: build
      run: dotnet build -c ${{ env.Configuration }}

    - name: test
      run: dotnet test --no-build --no-restore -c ${{ env.Configuration }}

    - name: pack
      run: dotnet pack --no-build --no-restore src/NetOfficeFw.Build.csproj -c ${{ env.Configuration }} -o dist

    - name: archive
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: NetOfficeFw.Build-${{ env.VersionSuffix }}.${{ matrix.configuration }}.nupkg
        path: dist/NetOfficeFw.Build.*.nupkg
