name: build

on:
  push:
    branches: [ main, nuspec ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-2022

    env:
      Configuration: ${{ matrix.configuration }}

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6

    - name: setup msbuild
      uses: microsoft/setup-msbuild@v1

    - name: build
      run: dotnet build

    - name: pack
      run: dotnet pack src/NetOfficeFw.Build.csproj

    - name: archive
      uses: actions/upload-artifact@v3
      with:
        name: NetOfficeFw.Build.nupkg
        path: src/bin/${{ matrix.configuration }}/NetOfficeFw.Build.*.nupkg
