name: build

on:
  push:
    branches: [ main, build ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-2022

    env:
      Configuration: ${{ matrix.configuration }}

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6

    - name: setup msbuild
      uses: microsoft/setup-msbuild@v1

    - name: build
      run: dotnet build
